API_KEY: Your_API_Key
CASH: 5000
RISK_FACTOR: 0.0025

# Choose your universe!
# Only those stocks are considered which are included in the enabled indexes
SP500: true
NQ100: false
SP400: false
SP600: false

TICKERS_API: "https://api.tdameritrade.com/v1/marketdata/%s/pricehistory"
