# TD Ameritrade Config
API_KEY: Your_API_Key
TICKERS_API: "https://api.tdameritrade.com/v1/marketdata/%s/pricehistory"

# Portfolio Cash Value in $
CASH: 5000
# Arbitrary risk factor, the higher the factor the bigger each individual position
RISK_FACTOR: 0.0025
# How many stocks do you want to see in the end?
STOCKS_COUNT_OUTPUT: 50

# Choose your universe!
# Only those stocks are considered which are included in the enabled indexes
SP500: true
NQ100: false
SP400: false
SP600: false
