# Data Retrieval
# Available Sources: YAHOO, TD_AMERITRADE
DATA_SOURCE: YAHOO
API_KEY: Your_API_Key
TICKERS_API: "https://api.tdameritrade.com/v1/marketdata/%s/pricehistory"

# Portfolio Cash Value in $
CASH: 5000
# Arbitrary risk factor, the higher the factor the bigger each individual position
RISK_FACTOR: 0.0020
# Optional: Instead of RISK_FACTOR you can directly say how many positions you want in the portfolio
# Result is not exact!
POSITIONS_COUNT_TARGET: 30
# How many stocks do you want to see in the end? This is just for info.
STOCKS_COUNT_OUTPUT: 50

# Choose your universe!
# Only those stocks are considered which are included in the enabled indexes
NQ100: true
SP500: true
SP400: false
SP600: false

# Calculation
# Standard is 90, but you can have as many as you want
MOMENTUM_CALCULATION_PAST_DAYS:
  - 90
  # - 120
  # - 250
